[package]
name = "ytm-cli"
version = "0.2.0"
default-run = "ytm-tui"
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "ytm-tui"
path = "src/main.rs"

[dependencies]
ytm-core = { path = "../ytm-core" }
ytm-player = { path = "../ytm-player" }
ytm-tui = { path = "../ytm-tui" }
clap.workspace = true
thiserror.workspace = true
color-eyre.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
tokio.workspace = true
futures.workspace = true
souvlaki.workspace = true
directories.workspace = true
toml.workspace = true
serde.workspace = true
ratatui.workspace = true
image.workspace = true
reqwest.workspace = true
crossterm.workspace = true

[dev-dependencies]
ytm-core = { path = "../ytm-core", features = ["mock"] }
ytm-player = { path = "../ytm-player", features = ["mock"] }
